let reservedValues = {
    // каталог
    "Бензиновый": "Gasoline",
    "Гибрид": "Hybrid",
    "Электро": "Electric",
    "Цвет": "Color",
    "Комплектация": "Complectation",
    "Подробнее": "More",
}

const catalogValues = {
    "Toyota Crown в самой доступной комплектации XLE представляет собой роскошный автомобиль. Особенностью этой модели является тканевая обивка в салоне, тогда как в более дорогих комплектациях предусмотрен кожаный салон.": "Toyota Crown in the most affordable configuration XLE is a luxury car. A feature of this model is the fabric upholstery in the cabin, while in more expensive trim levels a leather interior is provided.",
    "Acura TLX — современный представительский седан с мощными LED-фарами. Фирменная решетка радиатора, противотуманные светодиодные фары и сплиттер являются оригинальными украшениями передней части автомобиля.": "Acura TLX is a modern executive sedan with powerful LED headlights. The branded grille, LED fog lights and splitter are the original decorations of the front of the car.",
    "Acura RDX — компактный кроссовер, доступный в комплектациях с передним и полным приводом. Автомобиль оснащен турбированным четырехцилиндровым мотором на 272 л. с. и впечатляющим крутящим моментом в 380 Н∙м.": "The Acura RDX is a compact crossover SUV available in front-wheel drive and all-wheel drive. The car is equipped with a turbocharged four-cylinder engine with 272 hp. With. and an impressive torque of 380 Nm.",
    "MDX — трехрядный внедорожник премиум-класса вместительностью 7 человек. Acura MDX имеет привлекательный интерьер. Салон авто выполнен из качественных премиум-материалов.": "The MDX is a three-row premium SUV with a capacity of 7 people. The Acura MDX has an attractive interior. The interior of the car is made of high quality premium materials.",
    "Lexus NX — кроссовер с уникальным дизайном и высокотехнологичным исполнением. Особо жесткий кузов автомобиля гарантирует высокую пассивную безопасность пассажиров.": "Lexus NX is a crossover with a unique design and high-tech performance. The particularly rigid car body guarantees high passive safety for passengers.",
    "Lexus RX — полноприводный автомобиль с блокируемой вискомуфтой и межосевым дифференциалом. Он оснащен шестицилиндровым 3-литровым V-образным двигателем мощностью 204 л. с. и шестиступенчатой АКПП.": "Lexus RX is an all-wheel drive car with a lockable viscous coupling and a center differential. It is equipped with a six-cylinder 3-liter V-twin engine with 204 hp. With. and a six-speed automatic transmission.",
    "Lexus GX — большой внедорожник с независимой передней двойной рычажной подвеской. Конструкция обеспечивает комфортное передвижение по любым типам дорог. В комплекте идут постоянный полный привод и дисковые тормоза на все колеса.": "The Lexus GX is a large SUV with independent front double wishbone suspension. The design provides comfortable movement on any type of roads. Included are permanent four-wheel drive and disc brakes on all wheels.",
    "Lexus LX оснащен современными системами активной и пассивной безопасности. Пассажиры авто чувствуют себя комфортно даже при длительной поездке.": "Lexus LX is equipped with modern active and passive safety systems. Car passengers feel comfortable even during a long trip.",
    "Lexus IS имеет оригинальные кузовные панели, широкую решетку радиатора и узкие фары, а также агрессивный передний бампер. Базовая комплектация поставляется с 18-дюймовыми колесами.": "Lexus IS has original body panels, a wide grille and narrow headlights, as well as an aggressive front bumper. The basic equipment comes with 18-inch wheels.",
    "Lexus ES — седан бизнес-класса с богатой комплектацией и современным дизайном в спортивном стиле. Внешне автомобиль выглядит внушительно и агрессивно. Спереди он имеет узкие фары, большую веретенообразную решетку радиатора, эффектные колесные диски и низкие пороги и корпуса боковых зеркал заднего вида на узких ножках.": "Lexus ES is a business-class sedan with rich equipment and modern design in a sporty style. Externally, the car looks impressive and aggressive. At the front, it has narrow headlights, a large fusiform grille, eye-catching rims and low sills and side mirror housings on narrow legs.",
    "Внешний вид Dodge Charger внушительный и агрессивный. Автомобиль выглядит привлекательно и спортивно, но при этом солидно. Он обладает мощными фарами и крупной решеткой радиатора, рельефным профилем и стремительными очертаниями колесных арок. Задняя часть авто выделяется вытянутыми по всей ширине фонарями и массивным бампером с диффузором.": "The appearance of the Dodge Charger is impressive and aggressive. The car looks attractive and sporty, but at the same time solid. It has powerful headlights and a large grille, a relief profile and swift outlines of the wheel arches. The rear of the car is distinguished by lanterns stretched across the entire width and a massive bumper with a diffuser.",
    "Dodge Challenger — внушительное пятиместное купе на длинной колесной базе. Передние сиденья имеют боковую поддержку и множество регулировок. За счет массивного трансмиссионного тоннеля и выпуклых элементов комфортно разместиться на заднем ряду могут только двое пассажиров. Багажное отделение имеет объем в 459 л.": "The Dodge Challenger is an imposing five-seater long-wheelbase coupe. The front seats have lateral support and many adjustments. Due to the massive transmission tunnel and convex elements, only two passengers can comfortably accommodate in the back row. The luggage compartment has a volume of 459 liters.",
    "Dodge Durango — рестайлинговый кроссовер ранее известной модели. Он имеет агрессивные черты — узкие светодиодные фары и передний бампер с отдельными секциями по бокам.": "Dodge Durango is a restyled crossover of a previously famous model. It has aggressive features - narrow LED headlights and a front bumper with separate sections on the sides.",
    "Audi e-tron GT — современный электрический седан-купе, воплощающий в себе экоконцепцию немецкого автобренда. Автомобиль имеет элегантный экстерьер и комфортный салон, где всё на своих местах.": "The Audi e-tron GT is a modern electric coupe sedan embodying the eco-friendly concept of the German car brand. The car has an elegant exterior and a comfortable interior, where everything is in its place.",
    "Новый компактный электрический кроссовер Q4 e-tron оснащен платформой MEB от Volkswagen. Внешний вид модели исполнен в фирменном стиле Audi, а внутренний интерьер получил ряд обновлений, включая цифровую приборную панель и 10,1-дюймовый сенсорный дисплей MMI (с возможностью выбора опционального 11,6-дюймового дисплея).": "The new compact electric crossover Q4 e-tron is powered by Volkswagen's MEB platform. The exterior of the model is sporting Audi signature styling, while the interior has received a number of upgrades, including a digital instrument cluster and a 10.1-inch MMI touchscreen display (with a choice of an optional 11.6-inch display).",
    "Audi Q8 e-tron нового поколения — электрокар с уникальным дизайном оптики и фирменной фальш-решеткой немецкого производителя. Даже в базовой комплектации присутствуют оригинальные диски с необычным дизайном спиц и выразительные ярко-красные тормозные суппорты.": "The new generation Audi Q8 e-tron is an electric car with a unique optics design and a proprietary false grille from a German manufacturer. Even in the basic configuration there are original wheels with an unusual design of the spokes and expressive bright red brake calipers.",
    "Audi Q8 Sportback e-tron — электрический купеобразный кроссовер с полным приводом. Рестайлинговая версия e-tron после обновления получила название Q8. Автомобиль представлен публике в 2022 году.": "The Audi Q8 Sportback e-tron is an all-wheel drive electric coupe crossover. The restyled version of e-tron after the update was called Q8. The car is presented to the public in 2022.",
    "Новый Audi Q5 стал еще более эффективным и динамичным, предлагая ряд технических возможностей. Благодаря улучшенным двигателям, значительному снижению массы и высоким показателям аэродинамики производителям удалось достичь выдающихся характеристик.": "The new Audi Q5 has become even more efficient and dynamic, offering a range of technical features. Thanks to improved engines, significant weight reduction and high aerodynamics, manufacturers have achieved outstanding performance.",
    "Спортивный Audi Sportback стильно и современно выглядит, им приятно управлять, и он разумно сочетает пассажирское и грузовое пространство по сравнению с базовым вариантом.": "The sporty Audi Sportback looks stylish and modern, it is a pleasure to drive, and it intelligently combines passenger and cargo space compared to the base variant.",
    "Audi SQ5 — компактный премиальный внедорожник. Он оснащен полным приводом и доступен с бензиновым 4-цилиндровым турбодвигателем, мощной гибридной установкой или мотором V6. По габаритам модель значительно превосходит Q3, но при этом выглядит не громоздко, как трехрядный Q7.": "The Audi SQ5 is a compact premium SUV. It is equipped with all-wheel drive and is available with a petrol 4-cylinder turbo engine, a powerful hybrid unit or a V6 engine. In terms of dimensions, the model significantly exceeds the Q3, but at the same time it does not look bulky, like the three-row Q7.",
    "Audi Q7 — кроссовер среднего размера со стильным дизайном, высокими технологиями, удобным салоном и отличными ходовыми качествами.": "The Audi Q7 is a mid-size crossover with stylish design, high technology, a comfortable interior and excellent driving performance.",
    "Audi SQ8 2023 года получил множество полезных опций и впечатляющий внешний вид. Он уверенно управляется на дороге и обеспечивает комфорт роскошного салона.": "The 2023 Audi SQ8 has been given a host of useful options and impressive looks. It handles confidently on the road and provides the comfort of a luxurious cabin.",
    "Audi A3 2023 представлен в компактном четырехдверном кузове. Автомобиль собрал в себе преимущества всего модельного ряда, предлагая их в более компактном и доступном исполнении. Среди конкурентов в классе премиум-автомобилей, таких как Acura Integra и BMW 2-series Gran Coupe, A3 является оптимальным выбором.": "Audi A3 2023 presented in a compact four-door body. The car has collected the advantages of the entire model range, offering them in a more compact and affordable design. Among competitors in the premium car class such as the Acura Integra and the BMW 2-series Gran Coupe, the A3 is the right choice.",
    "Автомобиль нового поколения Audi S3 — типичный представитель класса \"гольф\". Он впечатляет совершенным сочетанием стиля, производительности и функциональности.": "The new generation Audi S3 is a typical representative of the golf class. It impresses with the perfect combination of style, performance and functionality.",
    "Седан Audi A4 2023 года имеет классический дизайн, который сочетает в себе стиль и спортивность. Автомобиль оснащен турбированными четырехцилиндровыми двигателями: версия 40 с мощностью 201 лошадиная сила и версия 45 с мощностью 261 лошадиная сила.": "The 2023 Audi A4 sedan has a classic design that combines style and sportiness. The car is equipped with turbocharged four-cylinder engines: the 40 version with 201 horsepower and the 45 version with 261 horsepower.",
    "Toyota Tacoma 2022 — надежный выбор для города и бездорожья. Внешний вид автомобиля подчеркивает его качества. Агрессивные, но плавные формы и оригинальная решетка радиатора не позволят автомобилю затеряться на парковке.": "The 2022 Toyota Tacoma is a solid choice for city and off-road use. The appearance of the car emphasizes its qualities. Aggressive, but smooth shapes and original grille will not allow the car to get lost in the parking lot.",
    "Новый Prius — гибрид с захватывающим дизайном. Эта модель совмещает передовые технологии, экономичность и надежность. Элегантная силуэтная линия Prius впечатляет с любого ракурса благодаря плавным изгибам и точным деталям.": "The new Prius is a hybrid with an exciting design. This model combines advanced technology, efficiency and reliability. The Prius' elegant silhouette line impresses from any angle with smooth curves and precise details.",
    "Corolla — автомобиль, на который вы можете положиться благодаря его надежности и инновационным технологиям.": "Corolla is a car you can rely on for its reliability and innovative technology.",
    "Гибридный автомобиль Toyota Prius Prime 2023 стал ниже, шире и длиннее по сравнению с предыдущей моделью и выглядит спортивным. Кроме нового кузова, автомобиль получил улучшенную силовую установку.": "The 2023 Toyota Prius Prime hybrid is lower, wider and longer than the outgoing model and looks sporty. In addition to the new body, the car received an improved power plant.",
    "Спортивный флагман Toyota, GR Supra 2023 года, выгодно отличается от более спокойных седанов, хэтчбеков и внедорожников.": "Toyota's sporty flagship, the 2023 GR Supra, compares favorably with quieter sedans, hatchbacks and SUVs.",
    "В 2023 году дебютировало новое поколение 7-й серии — флагманского премиум-седана BMW. Его управляемость немного легче, чем у автомобиля прошлого года, благодаря изменениям в шасси и подвеске, включая новую систему управления задними колесами.": "In 2023, the new generation of the 7 Series, BMW's flagship premium sedan, debuted. Its handling is slightly lighter than last year's car thanks to changes to the chassis and suspension, including a new rear wheel steering system.",
    "На первый взгляд купе 4-й серии выглядит не только крупнее, но и эффектнее своего предшественника. Благодаря новым пропорциям автомобиль получился более спортивным и даже мускулистым. Это стало возможно благодаря множеству горизонтальных линий.": "At first glance, the 4 Series coupe looks not only larger, but also more spectacular than its predecessor. Thanks to the new proportions, the car turned out to be more sporty and even muscular. This was made possible by the many horizontal lines.",
    "BMW 3-й серии считается основателем класса современных спорт-седанов. На протяжении уже шести поколений эта серия продолжает устанавливать новые стандарты качества в динамике, дизайне, совмещая это с практичностью. Каждая деталь внешнего вида автомобиля обещает невероятное удовольствие от управления.": "The BMW 3 Series is considered the founder of the modern sports sedan class. For six generations this series has continued to set new standards in performance, design and practicality. Every detail of the car's appearance promises incredible driving pleasure.",
    "BMW X5 — первый за всю историю немецкого бренда полноценный внедорожник. Благодаря значительному дорожному просвету, постоянному полному приводу и независимой подвеске всех колес Х5 предназначен для вождения по дорогам любого качества.": "The BMW X5 is the first full-fledged SUV in the history of the German brand. Thanks to its significant ground clearance, permanent all-wheel drive and independent suspension of all wheels, the X5 is designed to drive on roads of any quality.",
    "Спортивный внедорожник с купеподобным силуэтом Audi SQ5 Sportback — универсальный автомобиль, предоставляющий многочисленные возможности по оптимизации пространства.": "The sporty SUV with a coupe-like silhouette, the Audi SQ5 Sportback is a versatile vehicle that offers numerous options for optimizing space.",
    "Удовольствие и комфорт от управления, спортивный внешний вид и просторный салон — все это Audi SQ7. Внутри семейного внедорожника можно наслаждаться новейшими мультимедийными решениями. Нажав на педаль акселератора, вы ощутите мощь V-образного 8-цилиндрового двигателя.": "Driving pleasure and comfort, a sporty look and a spacious interior - all this is the Audi SQ7. Inside the family SUV, you can enjoy the latest multimedia solutions. Stepping on the accelerator pedal, you will feel the power of the V-shaped 8-cylinder engine.",
    "Электрический кроссовер модели Audi Q4 e-tron Sportback — первый автомобиль немецкого бренда на платформе MEB, используемой вышедшими ранее Skoda Enyaq iV и Volkswagen ID.4.": "The Audi Q4 e-tron Sportback electric crossover is the first German brand to use the MEB platform used by the earlier Skoda Enyaq iV and Volkswagen ID.4.",
    "BMW X7 — роскошный трехрядный внедорожник. Хотя его грузовой отсек и задние сиденья не такие просторные, как у конкурентов, он может похвастаться легкостью вождения, а также впечатляющим выбором двигателей.": "The BMW X7 is a luxury three-row SUV. Although its cargo area and rear seats aren't as spacious as the competition, it boasts an easy ride as well as an impressive choice of engines.",
    "Новый Toyota Sienna 2023 напоминает внедорожник, но остается верным сути минивэна. С тихой кабиной и плавным ходом, мощным двигателем и прочной подвеской, Sienna предлагает комфорт, обеспечиваемый просторным и хорошо оборудованным интерьером.": "The new Toyota Sienna 2023 resembles an SUV, but stays true to the essence of a minivan. With a quiet and smooth ride, powerful engine and solid suspension, the Sienna offers the comfort of a spacious and well-equipped interior.",
    "Toyota Venza — впечатляющий представитель среднеразмерных внедорожников. Автомобиль основан на гибридной модели RAV4.": "The Toyota Venza is an impressive midsize SUV. The car is based on the RAV4 hybrid model.",
    "Mercedes GLE отличается характерным узнаваемым дизайном. Спереди автомобиль выглядит брутально и агрессивно. Он имеет массивный бампер и рельефный капот, головную оптику с двумя диодными скобами и увеличенную решетку радиатора.": "The Mercedes GLE has a distinctive, recognizable design. From the front, the car looks brutal and aggressive. It has a massive bumper and embossed hood, head optics with two diode brackets and an enlarged radiator grille.",
    "Mercedes C имеет стильный современный внешний вид. Седан отличается оригинальной передней решеткой с хромированными вставками и угловатыми светодиодными фарами. Рельефный капот придает авто спортивный стиль. Кузов с плавными линиями и изгибами обеспечивает хорошую аэродинамику.": "Mercedes C has a stylish modern look. The sedan features an original front grille with chrome inserts and angular LED headlights. The embossed hood gives the car a sporty style. Body with smooth lines and curves provides good aerodynamics.",
    "Тoyota Highlander (hybrid) 2023 оборудован новой бензиновой силовой установкой — 2,4-литровым турбированным двигателем. Четыре цилиндра обеспечивают мощность в 265 лошадиных сил с улучшенным крутящим моментом в 42- Н*м. Расход топлива л/100 км в городе — 6, на трассе — 5,6.": "Toyota Highlander (hybrid) 2023 is equipped with a new gasoline power plant - a 2.4-liter turbocharged engine. Four cylinders provide 265 horsepower with improved torque of 42 Nm. Fuel consumption l / 100 km in the city - 6, on the highway - 5.6.",
    "Toyota обновила полноразмерный пикап Tundra, оснастив его V-образным шестицилиндровым двигателем. Обновленная задняя подвеска на катушках обеспечивает комфортную поездку, что отличает авто от пикапов с рессорами.": "Toyota has updated the full-size Tundra pickup truck with a V-shaped six-cylinder engine. The redesigned rear suspension coils provide a comfortable ride that distinguishes the car from pickups with leaf springs.",
    "Спереди Mercedes E 350 оборудован светодиодной оптикой, сзади расположены горизонтальные фонари, частично заходящие на крышку багажника. Профиль седана получил колесные диски с новым дизайном.": "The Mercedes E 350 is equipped with LED optics at the front, horizontal lights at the rear, partially extending onto the trunk lid. The profile of the sedan received rims with a new design.",
    "Toyota Sequoia 2023 года — трехрядный внедорожник на базе платформы пикапа Tundra. Новая модель гораздо современнее Sequoia второго поколения, которая просуществовала более десяти лет.": "The 2023 Toyota Sequoia is a three-row SUV based on the Tundra pickup platform. The new model is much more modern than the second generation Sequoia, which lasted more than a decade.",
    "Toyota RAV4 2023 года продолжает традицию просторного интерьера, привлекательной базовой цены и безопасности на дороге.": "The 2023 Toyota RAV4 continues the tradition of a spacious interior, attractive base price and road safety.",
    "Флагманом в линейке Tundra является гибридная модель i-FORCE MAX с 437 лошадиными силами при 5200 об/мин и крутящим моментом в 790 Нм при низких 2400 об/мин.": "The flagship in the Tundra line is the i-FORCE MAX hybrid model with 437 horsepower at 5200 rpm and 790 Nm of torque at a low 2400 rpm.",
    "Honda Civic 2022 года имеет несколько комплектаций: LX, Sport, EX, EX-L и Touring. Внешние параметры модели отличают оригинальность и высокий класс дизайнерского исполнения.": "The 2022 Honda Civic has multiple trim levels: LX, Sport, EX, EX-L, and Touring. The external parameters of the model are distinguished by originality and a high class of design performance.",
    "Ford Edge — крупноразмерный кроссовер с длиной 5 м. Своими габаритами и внешним видом он почти приблизился к моделям нового поколения ford explorer. В то же время Edge все еще базируется на переднеприводной платформе.": "Ford Edge is a large crossover with a length of 5 m. With its dimensions and appearance, it almost approached the models of the new generation of ford explorer. At the same time, Edge is still based on a front-wheel drive platform.",
    "Ford Explorer — стильный современный внедорожник с обновленным интерьером и оригинальными технологическими решениями. Автомобиль имеет немаленькие габариты — его колесная база превышает 3 м. При этом его нельзя назвать массивным.": "Ford Explorer is a stylish modern SUV with an updated interior and original technological solutions. The car has rather big dimensions - its wheelbase exceeds 3 m. At the same time, it cannot be called massive.",
    "Ford Mustang имеет все тот же узнаваемый классический дизайн оформления кузова. Длинный капот, покатая крыша и сдвинутый назад салон вместе с расширенными задними крыльями визуально делают автомобиль агрессивным. Широкая решетка радиатора дополнена тонкими светодиодными фарами.": "Ford Mustang has the same recognizable classic body design. A long hood, a sloping roof and a rear interior, along with extended rear fenders, make the car visually aggressive. The wide grille is complemented by slim LED headlights.",
    "Skoda Superb давно не выходила в новом кузове. Рестайлинговая версия может похвастаться угловатым дизайном передней решетки бампера и более гладкими фарами. Бампер имеет более выраженные отверстия вентиляции.": "Skoda Superb has not been released in a new body for a long time. The restyled version boasts an angular front bumper grille design and sleeker headlights. The bumper has more pronounced ventilation holes.",
    "Skoda Octavia внешне похожа на старшую модель Skoda Superb. Для автомобиля характерен сдержанный минималистичный дизайн. Кузов украшен выштамповками, визуально удлиняющими авто.": "The Skoda Octavia looks like the older Skoda Superb. The car is characterized by a discreet minimalistic design. The body is decorated with stampings that visually lengthen the car.",
    "Mercedes C Coupe обладает динамично-спортивным дизайном. Он имеет длинный капот и мощную поясную линию. Передняя часть авто внешне практически неотличима от седана, задняя часть выполнена в лучших традициях двухдверных авто бренда.": "Mercedes C Coupe has a dynamic and sporty design. It has a long hood and a powerful belt line. The front part of the car looks almost indistinguishable from the sedan, the rear part is made in the best traditions of the brand's two-door cars.",
    "Chevrolet Equinox — компактный и экономичный кроссовер, обладающий основными опциями безопасности. От своих предшественников модель отличается более дерзким внешним видом и скромными габаритами. Снаружи кроссовер выглядит агрессивно.": "The Chevrolet Equinox is a compact and fuel-efficient crossover with basic safety features. The model differs from its predecessors in a more daring appearance and modest dimensions. From the outside, the crossover looks aggressive.",
    "Chevrolet Blazer — среднеразмерный пятидверный SUV в переднеприводной или полноприводной комплектации. Blazer может похвастаться стильным экспрессивным дизайном, современной и производительной техникой, практичностью в эксплуатации и качественным оснащением.": "The Chevrolet Blazer is a mid-size five-door SUV available in either front-wheel drive or all-wheel drive. Blazer boasts a stylish expressive design, modern and productive technology, practicality in operation and high-quality equipment.",
    "Porsche Panamera — люксовый пятидверный седан с задним приводом в базовой комплектации. Экстерьер автомобиля выдержан в спортивном стиле. Аэродинамически отточенные формы сочетаются с вытянутыми чертами и эффектной светотехникой.": "The Porsche Panamera is a luxury five-door sedan with rear-wheel drive as standard. The exterior of the car is designed in a sporty style. Aerodynamically honed forms are combined with elongated features and spectacular lighting technology.",
    "Porsche Cayenne отличается оригинальным дизайном. Новая модель имеет четко очерченные фары головного света и объединенную с воздухозаборниками решетку радиатора, а также характерные выштамповки на капоте. Сзади авто украшают стильные узкие фонари, соединенные в одну линию за счет габаритных огней. Внедорожник уверенно стоит на 19-дюймовых колесах.": "The Porsche Cayenne has an original design. The new model has well-defined headlights and a radiator grille combined with air intakes, as well as characteristic stampings on the hood. Behind the car is decorated with stylish narrow lights, connected in one line due to marker lights. The SUV stands confidently on 19-inch wheels.",
    "Mazda CX-5 — пятидверный брутальный кроссовер. Передняя часть может похвастаться колючим взглядом фар, переходящих в пятигранную радиаторную решетку. Экстерьер авто запоминается выразительным силуэтом и энергичными очертаниями. Задняя часть автомобиля имеет выраженные фонари.": "Mazda CX-5 is a five-door brutal crossover. The front part boasts a sharp look of headlights, turning into a five-sided grille. The exterior of the car is remembered for its expressive silhouette and energetic outlines. The back of the car has pronounced lights.",
    "Mazda 3 выделяется стильным передним бампером и передней решеткой радиатора. Модель комплектуется адаптивным светодиодным светом головных фар и противотуманками. Боковые зеркала имеют повторители поворотов, а задний бампер украшает оригинальная имитация воздухозаборника.": "Mazda 3 stands out with a stylish front bumper and front grille. The model is equipped with adaptive LED headlights and fog lights. The side mirrors have repeaters, and the rear bumper is decorated with an original imitation of the air intake.",
    "Mazda CX-9 — пятидверный полноразмерный семиместный кроссовер. SUV предлагается с передним или полным приводом и отличается выразительным дизайном, а также богатым набором различных опций.": "Mazda CX-9 is a five-door full-size seven-seater crossover. The SUV is available with front-wheel drive or all-wheel drive and is distinguished by its expressive design, as well as a rich set of various options.",
    "Audi RS3 существенно отличается от базовой модели в линейке. Турбированный двигатель RS3 объемом 2,5 литра с пятью цилиндрами развивает внушительный крутящий момент в 500 Нм и передает его на все четыре колеса через быстросменную семиступенчатую автоматическую трансмиссию с двумя сцеплениями и систему полного привода Quattro от Audi.": "The Audi RS3 is significantly different from the base model in the lineup. The turbocharged 2.5-liter five-cylinder RS3 engine develops an impressive 500 Nm of torque and sends it to all four wheels through a quick-change seven-speed dual-clutch automatic transmission and Audi's Quattro all-wheel drive system.",
    "Audi RS Q8 — самый мощный внедорожник-купе от Audi Sport. В дополнение к традиционной для RS динамике, он поражает невероятной изменчивостью впечатлений от управления и дизайна.": "The Audi RS Q8 is the most powerful SUV coupe from Audi Sport. In addition to the traditional RS dynamics, it impresses with its incredible variability in driving experience and design.",
    "Audi SQ8 позволяет ощутить мощность под капотом с первого касания педали газа. Шасси Q8 обеспечивает точное и уверенное управление с мягкой подвеской. Автомобиль является доступной альтернативой полноразмерному люкс-седану A8.": "Audi SQ8 allows you to feel the power under the hood from the first touch of the gas pedal. The Q8 chassis provides precise and confident handling with soft suspension. The car is an affordable alternative to the full-size A8 luxury sedan.",
    "Lexus RC 2023 в моделях RC300 и RC350 имеют мягкую подвеску и комфортный интерьер. Стандартным для авто является четырехцилиндровый турбированный двигатель, но при выборе полного привода или более дорогой комплектации RC350 будет доступен атмосферный 3,5-литровый V6.": "Lexus RC 2023 models RC300 and RC350 have a soft suspension and a comfortable interior. A four-cylinder turbocharged engine is standard on the car, but a naturally aspirated 3.5-liter V6 will be available when choosing all-wheel drive or the more expensive RC350 trim.",
    "Honda CR-V 2023 в новом дизайне впечатляет своим привлекательным видом и дополняется современными технологиями, включая информационно-развлекательную систему с девятидюймовым сенсорным экраном и поддержку беспроводного Apple CarPlay и Android Auto.": "The redesigned Honda CR-V 2023 impresses with its attractive looks and is complemented by modern technologies, including a nine-inch touchscreen infotainment system and support for wireless Apple CarPlay and Android Auto.",
    "Honda CR-V Hybrid 2023 получила ряд улучшений по сравнению с предыдущей гибридной моделью CR-V. Honda улучшила настройку бесступенчатой автоматической трансмиссии (CVT), чтобы она больше напоминала традиционный автомат и имитировала переключение передач в большинстве ситуаций.": "The 2023 Honda CR-V Hybrid received a number of improvements over the previous CR-V hybrid model. Honda improved the setting of the continuously variable automatic transmission (CVT) to more closely resemble a traditional automatic and mimic gear changes in most situations.",
    "Toyota Camry 2020 предлагает разнообразные варианты силовых агрегатов: экономичный 4-цилиндровый двигатель, мощный V-образный 6-цилиндровый и экологичную гибридную систему.": "The 2020 Toyota Camry offers a variety of powertrain options: an economical 4-cylinder engine, a powerful V-shaped 6-cylinder and an environmentally friendly hybrid system.",
    "Внешний вид Toyota Camry XV70 по сравнению с прошлой моделью претерпел некоторые изменения. Внимание сразу акцентируется на новом бампере и колесных дисках, а также на новых вариантах окраски кузова. Интерьер был переработан, а системы безопасности — модернизированы.": "The appearance of the Toyota Camry XV70 has undergone some changes compared to the previous model. Attention immediately focuses on the new bumper and rims, as well as new body color options. The interior has been redesigned and the security systems upgraded.",
    "Chevrolet Menlo — электромобиль известного бренда, обладающий современным футуристическим дизайном. При создании авто производители вдохновлялись концептом Chevrolet FNR-X, представленным на Auto Shanghai в 2017 году.": "Chevrolet Menlo is an electric car of a well-known brand with a modern futuristic design. When creating cars, manufacturers were inspired by the Chevrolet FNR-X concept presented at Auto Shanghai in 2017.",
    "Toyota C-HR Electric — электрическая версия модели Toyota C-HR. Электромобиль сделан на собственной архитектуре E-TNGA и оснащен задней многорычажной подвеской, оригинальной комплектацией и усиленными элементами шасси.": "Toyota C-HR Electric is an electric version of the Toyota C-HR. The electric car is made on its own E-TNGA architecture and is equipped with a rear multi-link suspension, original equipment and reinforced chassis elements.",
    "VELITE 7 — первый электрокроссовер в новой серии Buick, который имеет ходовой запас в 500 км с циклом NEDC.": "The VELITE 7 is the first electric crossover in the new Buick series that has a range of 500 km with the NEDC cycle.",
    "BYD Dolphin — оригинальный электромобиль, который отличается оптимальным соотношением цены и качества и популярен как в Китае, так и за его пределами. Дизайн хэтчбека продуман до мельчайших деталей и сочетает футуризм и сдержанность.": "The BYD Dolphin is an original electric vehicle that is value for money and is popular both in China and beyond. The design of the hatchback is thought out to the smallest detail and combines futurism and restraint.",
    "Geely M6 — это обновленная версия модели Geometry C. При ее создании компания работала вместе с Huawei, что привело к появлению цифровой кабины и полному набору услуг HarmonyOS.": "The Geely M6 is an upgraded version of the Geometry C model. The company worked with Huawei to create it, resulting in a digital cockpit and full HarmonyOS services.",
    "BMW iX3 — электромобиль класса K2 с задним приводом, представляющий 1-е поколение модели. Спортивный вид кроссовера обеспечивают пакет M Sport и силовая установка.": "The BMW iX3 is a rear-wheel drive K2 electric vehicle representing the 1st generation of the model. The sporty look of the crossover is provided by the M Sport package and the power plant.",
    "Кроссовер BYD Tang, второе поколение которого было выпущено в Китае в 2018 году, представляет собой автомобиль, доступный в пяти- и семиместной версиях. Дизайн создан при участии Вольфганга Эггера, экс-шеф-дизайнера Alfa Romeo и Audi.": "The BYD Tang crossover, the second generation of which was released in China in 2018, is a vehicle available in five- and seven-seater versions. The design was created with the participation of Wolfgang Egger, ex-chief designer of Alfa Romeo and Audi.",
    "В 2021 году был запущен в производство электромобиль GAC Toyota iA5, предназначенный для среднего сегмента китайского рынка. Литий-ионная батарея и двигатель мощностью 135 кВт обеспечивает до 510 километров езды без подзарядки.": "In 2021, the GAC Toyota iA5 electric car was launched, designed for the middle segment of the Chinese market. The lithium-ion battery and 135 kW motor provide up to 510 kilometers of driving without recharging.",
    "Geometry E — это новый электрический кроссовер, который создан для молодых людей, ценящих необычный дизайн и доступную цену.": "Geometry E is a new electric crossover that is designed for young people who appreciate unusual design and affordable price.",
    "Honda и Dongfeng представили электрокроссовер M-NV, разработанный на основе архитектуры Honda HR-V или X-NV. M-NV оснащен более мощным аккумулятором, что обеспечивает значительный запас хода. Зарядка на 125 кВт позволяет получить до 80 % батареи за 38 минут.": "Honda and Dongfeng have unveiled the M-NV electric crossover, based on the Honda HR-V or X-NV architecture. M-NV is equipped with a more powerful battery, which provides a significant range. Charging at 125 kW allows you to get up to 80% of the battery in 38 minutes.",
    "Hyundai Mistra — это небольшой седан, созданный специально для китайского рынка и занимающий место между моделями Elantra и Sonata в линейке Hyundai. Модель вышла на рынок в 2013 году, а спустя 4 года, в 2017-м, ее обновили. В электрической версии установлен двигатель 135 кВт с крутящим моментом 310 Нм и литий-ионной батареей.": "The Hyundai Mistra is a small sedan designed specifically for the Chinese market and sits between the Elantra and Sonata models in Hyundai's lineup. The model entered the market in 2013, and 4 years later, in 2017, it was updated. The electric version has a 135 kW motor with 310 Nm of torque and a lithium-ion battery.",
    "Электрический кроссовер Lexus UX 300e обеспечит водителям наслаждение при езде по городу или на извилистых загородных дорогах. Автомобиль гарантирует легкость в управлении за счет низкого центра тяжести и жесткого шасси.": "The Lexus UX 300e electric crossover will provide drivers with an enjoyable ride in the city or on winding country roads. The car guarantees ease of driving due to the low center of gravity and rigid chassis.",
    "Nissan Ariya — первый полноценный электромобиль марки Nissan, выпущенный почти через 10 лет после хэтчбека Nissan Leaf. Ariya — это новое видение электрокара, сочетающее в себе силу, точность и стиль. Флагманская модель с новой эмблемой и тонкими LED-фарами имеет такие же размеры, как и кроссовер Nissan X-Trail, но превосходит его по размеру колесной базы.": "Nissan Ariya is Nissan's first full-fledged electric car, released almost 10 years after the Nissan Leaf hatchback. Ariya is a new vision of the electric car that combines power, precision and style. With a new emblem and slim LED headlights, the flagship model is the same size as the Nissan X-Trail crossover but has a larger wheelbase.",
    "Model Y — электрический кроссовер, выпускаемый компанией Tesla. Производство этой модели началось во Фримонте в январе 2020 года, а первые поставки состоялись 13 марта того же года.": "Model Y is an electric crossover produced by Tesla. Production of this model began in Fremont in January 2020, and the first deliveries took place on March 13 of the same year.",
    "Автомобиль Volkswagen ID.3 обладает инновационным дизайном, сочетающим практичность и привлекательный внешний вид. Авто создано для тех, кто стремится к изменениям и готов активно использовать технологии в современной жизни.": "The Volkswagen ID.3 has an innovative design that combines practicality with good looks. The car was created for those who strive for change and are ready to actively use technology in modern life.",
    "Volvo представила новый компактный кроссовер XC40 с уникальным скандинавским дизайном. Он имеет смелое и четкое проектирование, идеально подходящее для городской среды.": "Volvo has introduced a new compact crossover XC40 with a unique Scandinavian design. It has a bold and clear design, ideal for urban environments.",
    "Weltmeister W6 — это среднегабаритный кроссовер от китайской компании NEV WM Motor. Массово автомобиля начали производить в январе 2021-го. Он был разработан совместно с компанией Baidu.": "Weltmeister W6 is a mid-size crossover from the Chinese company NEV WM Motor. Mass production of the car began in January 2021. It was developed in cooperation with Baidu.",
    "Weltmeister EX5 — это новый электровнедорожник, разработанный китайским стартапом WM Motor Technology Co. Название бренда с немецкого переводится как “мировой чемпион”.": "The Weltmeister EX5 is a new electric SUV developed by Chinese startup WM Motor Technology Co. The brand name is translated from German as “world champion”.",
    "Wuling Mini EV — это компактный электрокар, который выглядит как Smart. Он рассчитан на четырех пассажиров и возглавляет рейтинг самых часто покупаемых электрокаров в Китае. За 2 года продано около 400 000 экземпляров.": "Wuling Mini EV is a compact electric car that looks like Smart. It is designed for four passengers and leads the ranking of the most frequently bought electric cars in China. In 2 years, about 400,000 copies were sold.",
    "XPeng P5 — новый электрический седан от Xiaopeng Motors. Этот автомобиль конкурирует с моделями из ДВС Toyota Camry и Honda Accord.": "XPeng P5 is a new electric sedan from Xiaopeng Motors. This car competes with ICE models Toyota Camry and Honda Accord.",
    "NIO EC6 — это второй автомобиль в серии NIO, которая начала свой путь как стартап в сотрудничестве с производителем JAC из Китая. Авто называют серьезным конкурентом Tesla.": "The NIO EC6 is the second car in the NIO series, which began as a start-up in collaboration with Chinese manufacturer JAC. The car is called a serious competitor to Tesla.",
    "ID.4 от Volkswagen является новейшим кроссовером, который победил на конкурсе World Car of the Year 2021. Этот электромобиль воплощает немецкое качество, 30-летний опыт в производстве авто и новые технологии. Он предлагает большой запас хода, безопасность, стильный дизайн и широкий выбор комплектаций.": "The ID.4 from Volkswagen is the latest SUV to win the World Car of the Year 2021 award. This electric vehicle embodies German quality, 30 years of automotive experience and new technologies. It offers a long range, safety, stylish design and a wide range of trim levels.",
    "ID.4 X от Volkswagen — это внедорожник, который на 100 % работает от электричества. Он произведен на архитектуре модульного электропривода MEB. Концепцию дизайна можно охарактеризовать как \"легкий ритм речи\", где присутствуют полная форма и подвижные линии.": "ID.4 X from Volkswagen is an SUV that is 100% powered by electricity. It is produced on MEB modular electric drive architecture. The design concept can be described as \"light rhythm of speech\", where there is a full form and moving lines.",
    "Volkswagen ID.6 — трехрядный электрокроссовер, который производится в Китае и входит в серию ID. Основан на архитектуре MEB.": "The Volkswagen ID.6 is a three-row electric crossover made in China and part of the ID series. Based on MEB architecture.",
    "Электрический внедорожник Volkswagen ID.6 X создает новый стандарт качества, так как в нем максимально учтены потребности водителя и пассажиров.": "The Volkswagen ID.6 X electric SUV sets a new quality standard, as it takes into account the needs of the driver and passengers as much as possible.",
    "ORA Good Cat — стильный хэтчбек, который не оставит вас равнодушным. Большой панорамный люк позволит наслаждаться окружающим миром, а модный дизайн и инновационные функции оставят незабываемые впечатления.": "ORA Good Cat is a stylish hatchback that won't leave you indifferent. The large panoramic sunroof lets you enjoy the world around you, while the trendy design and innovative features make for an unforgettable experience.",
    "Polestar 2 от компании Volvo — пятидверный электромобиль с кузовом в стиле фастбэк. Доступен в нескольких вариантах комплектаций и может проехать до 335 миль без подзарядки.": "Volvo's Polestar 2 is a five-door fastback electric car. Available in several trim levels and can go up to 335 miles on a single charge.",
    "Компания Roewe, являющаяся частью SAIC, выпустила универсал EI5, разработанный только в электрическом варианте. Размеры автомобиля почти идентичны Ford Focus: длина — 4544 мм, ширина — 1818 мм, высота — 1509 мм, база колес — 2665 мм.": "Roewe, which is part of SAIC, has released the EI5 station wagon, developed only in an electric version. The dimensions of the car are almost identical to the Ford Focus: length - 4544 mm, width - 1818 mm, height - 1509 mm, wheelbase - 2665 mm.",
    "Shenlan SL03 — электрический компактный седан класса F, производимый китайской компанией Changan Automobile под брендом NEV Shenlan.": "The Shenlan SL03 is an F-class electric compact sedan manufactured by China's Changan Automobile under the NEV Shenlan brand.",
    "Первый электромобиль японского бренда Toyota под названием Toyota bZ4X, предназначенный для широких масс, появился в продаже в начале 2022-го. BZ в названии означает \"за пределами ноля\" и подчеркивает стремление компании создать электромобиль без выбросов вредных веществ.": "The first electric car of the Japanese brand Toyota called Toyota bZ4X, designed for the masses, went on sale in early 2022. The BZ in the name means \"beyond zero\" and underscores the company's commitment to a zero-emission electric vehicle.",
    "NETA V является городским автомобилем в стиле Touchable Smart EV, который разработан с учетом надежной аэродинамики. В стандартной комплектации электромобиль оснащен мотором мощностью 40 кВт (55 л. с.) и вращающим моментом 110 Н*м, что обеспечивает ускорение до 50 км/ч за 5,9 секунды и максимальную скорость 102 км/ч.": "NETA V is a Touchable Smart EV style urban vehicle designed with robust aerodynamics in mind. As standard, the electric vehicle is equipped with a 40 kW (55 hp) motor and 110 Nm of torque, which ensures acceleration to 50 km/h in 5.9 seconds and a top speed of 102 km/h.",
    "Сочетание передовых технологий и спортивного стиля делает Neta S идеальным выбором для тех, кто ищет комфорт и безопасность за рулем.Узкая светодиодная оптика и наклонная линия кузова выглядят очень привлекательно. В комплектации 650 Yaoshi двери открываются вверх, как у Lamborghini.": "The combination of cutting-edge technology and sporty styling makes the Neta S the perfect choice for those who seek comfort and safety behind the wheel. The narrow LED optics and sloping body line look very attractive. On the 650 Yaoshi, the doors open up like a Lamborghini.",
    "Новый EQA от Mercedes-EQ сочетает в себе эффективную производительность и комфортное использование в повседневной жизни. Дизайн автомобиля выполнен со спортивным оттенком, в фирменном стиле бренда.": "The new EQA from Mercedes-EQ combines efficient performance with comfortable everyday use. The design of the car is made with a sporty touch, in the corporate style of the brand.",
    "MG 4 Electric, или Mulan, — это электрический хэтчбек, выпущенный компанией MG в июне 2022 года. Он построен на новой архитектуре, что позволило MG использовать более крупные аккумуляторы, сохранив при этом легкий вес автомобиля. Эту модель называют конкурентом Volkswagen ID.3.": "The MG 4 Electric, or Mulan, is an electric hatchback launched by MG in June 2022. It is built on a new architecture that has allowed MG to use larger batteries while keeping the car lightweight. This model is called a competitor to the Volkswagen ID.3.",
    "Презентация автомобиля Airtrek прошла в 2021-м на автовыставке в Китае, где он привлек внимание журналистов со всего мира благодаря своему дизайну и передовым технологиям. Airtrek отражает стиль дизайна Mitsubishi во всем — от его панели Dynamic Shield до шестиугольной формы дверей багажника, которые символизируют маневренность и стабильность.": "The presentation of the Airtrek car took place in 2021 at the auto show in China, where it attracted the attention of journalists from all over the world due to its design and advanced technologies. The Airtrek reflects Mitsubishi's design style in everything from its Dynamic Shield panel to the hexagonal shape of the tailgate, which symbolizes agility and stability.",
    "Компактный внедорожник Neta U был выпущен на рынок стартапом Hozon Auto из Китая. Он имеет гармоничные пропорции кузова, маневренную форму и лишен громоздкости, характерной для традиционных внедорожников. Консоль оборудована дисплеями панели приборов AMOLED и информационно-развлекательными системами. Комфорт водителя обеспечивается доступом без ключа, системой помощи, парктроником и другими функциями.": "The Neta U compact SUV was launched on the market by Chinese startup Hozon Auto. It has harmonious body proportions, an agile shape and is free from the bulkiness of traditional SUVs. The console is equipped with AMOLED instrument cluster displays and infotainment systems. Driver comfort is provided by keyless entry, assistance system, parking sensors and other functions.",
    "Компания Leap Motor из Китая представила новый электрический кроссовер, названный C11, на выставке в Гуанчжоу. Новинка имеет сходство с Tesla Model Y по размерам и характеристикам, однако стоит в 1,5 раза дешевле. C11 создан на основе собственной архитектуры и имеет длину 4745 мм, ширину 1890 мм, высоту 1635 мм и базу колес 2923 мм.": "China's Leap Motor has unveiled a new electric crossover, called the C11, at the Guangzhou show. The novelty is similar to the Tesla Model Y in terms of size and characteristics, but it costs 1.5 times cheaper. The C11 is based on its own architecture and measures 4745mm long, 1890mm wide, 1635mm high and has a 2923mm wheelbase.",
    "Mazda CX-30 — это компактный внедорожник 2022 года, который предназначен для поездок по городу и длительных путешествий. Авто славится уникальным дизайном и элегантным интерьером со множеством вариантов подключения.": "The Mazda CX-30 is a 2022 compact SUV that is designed for city driving and long hauls. The car is famous for its unique design and elegant interior with many connection options.",
    "Новая модель электрического кроссовера EQB от Mercedes объединила в себе все ключевые элементы дизайна бренда, предлагая комфорт и универсальность. Семиместное авто оснащено просторным грузовым отделением и инновационной информационно-развлекательной системой MBUX, обеспечивая водителю и пассажирам управление кроссовером.": "The new EQB electric crossover model from Mercedes combines all the brand's key design elements, offering comfort and versatility. The seven-seat vehicle is equipped with a spacious cargo area and the innovative MBUX infotainment system, giving the driver and passengers control of the crossover.",
    "Mercedes-Benz EQC — машина, которая сочетает в себе множество классических преимуществ бренда, таких как высокое качество, надежность и комфорт. Двигатели, встроенные в переднюю и заднюю оси, общей мощностью 408 л. с. (300 кВт) в сочетании с интеллектуальной технологией управления позволяют получить высокие динамические характеристики и многокилометровую дальность хода на электрическом тяге.": "Mercedes-Benz EQC is a car that combines many classic brand advantages such as high quality, reliability and comfort. Engines built into the front and rear axles, with a total power of 408 hp. With. (300 kW) in combination with intelligent control technology allow you to get high dynamic performance and many kilometers of electric driving range.",
    "Hongqi E-HS9 2021 года выпуска в Китае сравнивают с автомобилем Rolls Royce за его роскошь и престижность. Бренд Hongqi, который является частью автохолдинга FAW, специализируется на премиум-автомобилях.": "The 2021 Hongqi E-HS9 is compared to Rolls Royce in China for its luxury and prestige. The Hongqi brand, which is part of the FAW auto holding, specializes in premium cars.",
    "В автомобиле T03 предусмотрено огромное количество функций, благодаря которым вождение становится безопасным и комфортным. Наиболее значимые из них — адаптивный круиз-контроль, автоматическое экстренное торможение, поддержка полосы движения и определение уровня усталости водителя. Всеми этими функциями легко управлять с помощью цифрового экрана, подключенного к мультимедийной системе и установленного в салоне.": "The T03 is equipped with a huge number of features that make driving safer and more comfortable. The most significant of these are adaptive cruise control, automatic emergency braking, lane keeping and driver fatigue detection. All these functions are easy to control using a digital screen connected to the multimedia system and installed in the cabin.",
    "BYD Qin Plus выделяется своей утонченностью. Большая решетка Dragon Face сочетается с хромированными молдингами, а трехмерные фары и фонари сзади делают авто дерзким и стильным.": "BYD Qin Plus stands out for its sophistication. The large Dragon Face grille is paired with chrome moldings, while the 3D headlights and taillights make the car look bold and stylish.",
    "BYD Han EV представляет собой автомобиль с привлекательным и дорогим внешним видом, который сочетает в себе элементы классического китайского и европейского стиля.": "BYD Han EV is an attractive and expensive looking vehicle that combines elements of classical Chinese and European style.",
    "LYRIQ — автомобиль, в котором гармонично сочетаются стиль, технологии и цвет. Он работает на платформе Ultium EV, обеспечивая спортивный и маневренный привод. Модель оснащена технологией помощи водителю Super Cruise и встроенной системой Google.": "LYRIQ is a car that harmoniously combines style, technology and color. It runs on the Ultium EV platform, providing a sporty and agile drive. The model is equipped with Super Cruise driver assistance technology and built-in Google system.",
    "Changan Lumin — новый доступный электромобиль, который является конкурентной моделью на рынке. Внешне авто смотрится привлекательно благодаря гладким формам, круглой оптике и выдвигающимся ручкам. Модель разработана на основе архитектуры EPA0, созданной специально для легковых автомобилей. Имеет габариты 3270 x 1700 x 1545 мм и базу колес 1980 мм.": "Changan Lumin is a new affordable electric vehicle that is a competitive model in the market. Externally, the car looks attractive thanks to its smooth shapes, round optics and retractable handles. The model was developed on the basis of the EPA0 architecture, created specifically for passenger cars. It has dimensions of 3270 x 1700 x 1545 mm and a wheelbase of 1980 mm.",
    "Dongfeng EX1 2022 — один из самых бюджетных кроссоверов на рынке. Однако, несмотря на доступную цену, он оснащен передовыми технологиями и имеет достойные технические характеристики.": "Dongfeng EX1 2022 is one of the most budget crossovers on the market. However, despite the affordable price, it is equipped with advanced technologies and has decent technical specifications.",
    "GAC представила премиальный кроссовер Aion LX на выставке Auto Shanghai в 2019 году. Главным преимуществом этой модели является большой запас хода. Этот автомобиль уже второй в линейке, выпущенный под брендом GAC New Energy Aion, после Aion S.": "GAC unveiled the premium crossover Aion LX at Auto Shanghai in 2019. The main advantage of this model is a large power reserve. This vehicle is the second in the line to be branded under the GAC New Energy Aion brand, after the Aion S.",
    "GAC Aion Y — компактный хэтчбек, выпускаемый китайским концерном GAC под отдельным суббрендом Aion с 2020 года. Это уже четвертая модель суббренда, предназначенная для молодого поколения.": "GAC Aion Y is a compact hatchback produced by the Chinese concern GAC under a separate sub-brand Aion since 2020. This is the fourth sub-brand model designed for the younger generation.",
    "Geely G6 — это обновленная версия Geometry A. Она обладает броским дизайном с крупными диодными фарами и закрытой светящейся панелью. Geely G6 — первый совместный проект Geely и Huawei. Результатом взаимодействия стала цифровая кабина, а также опции HarmonyOS, которые доступны владельцу авто.": "Geely G6 is an updated version of Geometry A. It has a catchy design with large LED headlights and a closed luminous panel. Geely G6 is the first joint project between Geely and Huawei. The result of the interaction was a digital cockpit, as well as HarmonyOS options that are available to the car owner.",
    "BYD Seal — компактный электроседан класса F. Автомобиль построен на базе новой архитектуры BYD — e-Platform 3.0 на 800 Вольт.": "BYD Seal is a compact class F electric sedan. The car is built on the basis of the new BYD architecture - e-Platform 3.0 at 800 volts.",
    "BYD Song PLUS — внедорожник, который обладает габаритами 4705/1890/1680 мм и базой колес 2765 мм. Это самый широкий электромобиль в своем классе, который обеспечивает комфортную езду.": "BYD Song PLUS is an SUV that has dimensions of 4705/1890/1680 mm and a wheelbase of 2765 mm. It is the widest electric car in its class and provides a comfortable ride.",
    "Автомобиль Audi Q4 e-tron — электрический кроссовер класса К2 с задним или полным приводом, созданный на основе платформы MEB от Volkswagen. Это премиальный автомобиль, аналогичный моделям Skoda Enyaq iV и Volkswagen ID.4.": "The Audi Q4 e-tron is an electric K2 class crossover with rear or all-wheel drive, based on the MEB platform from Volkswagen. This is a premium car similar to the Skoda Enyaq iV and Volkswagen ID.4 models.",
    "Audi Q5 e-tron — роскошный кроссовер среднего размера, имеющий аккумуляторную батарею и 3-рядные сиденья. Производится компанией Audi на совместном предприятии SAIC-VW в Китае. Основан на платформе MEB и является пятой электрической моделью серии Audi e-tron, которая тесно связана с Q4 e-tron.": "The Audi Q5 e-tron is a luxury mid-size crossover with a battery pack and 3-row seats. Produced by Audi at the SAIC-VW joint venture in China. Based on the MEB platform, it is the fifth electric model in the Audi e-tron series and is closely related to the Q4 e-tron.",
    "BMW i4 — это первый электромобиль Gran Coupe, который сочетает в себе прекрасную динамику и стопроцентный комфорт. Этот пятидверный автомобиль был создан на базе привода BMW eDrive 5-го поколения и имеет спортивный дизайн.": "The BMW i4 is the first all-electric Gran Coupé to combine excellent driving dynamics with 100% comfort. Based on the 5th generation of BMW eDrive, this five-door vehicle has a sporty design.",
    "VELITE 6 — мультифункциональный электромобиль (MAV), который производится компанией SAIC-GM под маркой Buick. Он идеально подходит для городской езды, предлагая практичность и удобство. Современная электроника делает вождение легким и простым.": "The VELITE 6 is a multifunctional electric vehicle (MAV) manufactured by SAIC-GM under the Buick brand. It is ideal for city driving, offering practicality and convenience. Modern electronics make driving easy and simple.",
    "Byd E2, вышедший в массовое производство в 2021 году, — это электрический хэтчбек с передним приводом. Компания выпустила первую модель серии только в апреле 2019 года. Элегантный 5-дверный хэтчбек гармонично дополняет модельный ряд китайского бренда.": "Byd E2, which went into mass production in 2021, is a front-wheel drive electric hatchback. The company released the first model of the series only in April 2019. An elegant 5-door hatchback harmoniously complements the lineup of the Chinese brand.",
    "BYD Yuan Pro — обновленный электрический кроссовер с батареей Blade. Новый электрокар предназначен для использования всей семьей. При умеренной стоимости авто имеет обширную комплектацию, в том числе системы безопасности и помощи водителю.": "BYD Yuan Pro is an updated electric crossover with a Blade battery. The new electric car is designed for use by the whole family. At a moderate cost, the car has an extensive package, including security systems and driver assistance.",
    "BYD Yuan Plus — это электрокроссовер, который сразу же привлекает внимание инновационным внешним видом и функциональностью. Он основан на архитектуре BYD 3.0 и выполнен в дизайне Dragon Face 3.0.": "The BYD Yuan Plus is an electric SUV that immediately grabs attention with its innovative look and functionality. It is based on the BYD 3.0 architecture and features the Dragon Face 3.0 design.",
    "Zeekr 001 — это первый электромобиль китайского производителя Geely. Дата выпуска — октябрь 2021 года. Внешне автомобиль похож на Porsche Panamera.": "The Zeekr 001 is the first electric car from the Chinese manufacturer Geely. The release date is October 2021. Externally, the car is similar to the Porsche Panamera.",
    "ZEEKR X — электромобиль китайского бренда Geely, выпущенный для европейского рынка.": "ZEEKR X is an electric car of the Chinese brand Geely, released for the European market.",
    "Электрокар Chery под названием Ant создан совместно с итальянской студией Pininfarina, отвечающей за дизайн автомобиля.": "The Chery electric car called Ant was created in collaboration with the Italian studio Pininfarina, which is responsible for the design of the car.",
    "Автомобиль AITO M5 с гибким и динамичным кузовом, сопротивлением ветру 0,32 Cd и изящным дизайном — это сочетание элегантности и мощи.": "With its flexible and dynamic body, 0.32 Cd wind resistance and sleek design, AITO M5 is a combination of elegance and power.",
    "Audi Q2 — это компактный кроссовер премиум-класса, созданный и изготовленный компанией Audi. Q2L e-tron — электрическая версия этой модели.": "The Audi Q2 is a premium compact SUV designed and manufactured by Audi. Q2L e-tron is the electric version of this model.",
    "BMW i3 — первый электромобиль премиум-класса, произведенный для работы без вредных выбросов в окружающую среду.": "The BMW i3 is the first premium electric vehicle designed to operate without harmful emissions to the environment.",
    "Электромобиль Dongfeng, базирующийся на Renault City K-ZE, — это улучшенная версия модели Dongfeng EX1 Pro.": "Based on the Renault City K-ZE, the Dongfeng electric car is an improved version of the Dongfeng EX1 Pro model.",
    "Электрокроссовер является творением экспертов в области электромобилей, но, несмотря на это, заслуживает право носить имя Мустанг.": "The electric crossover is the creation of experts in the field of electric vehicles, but despite this, it deserves the right to bear the Mustang name.",
    "Первый представитель линейки \"e:N\" — электромобиль e:NS1 — объединил в себе оригинальный дизайн, страсть и спорт, характерные для бренда Honda. Модель получила современную электрификацию и смарт-технологии.": "The first member of the \"e:N\" range, the e:NS1 electric car, combines the original design, passion and sport that are characteristic of the Honda brand. The model received modern electrification and smart technologies.",
    "Седан Tesla Model 3 был представлен 31 марта 2016 года. Пятиместный автомобиль создан на новой платформе, отличающейся от используемой в Tesla Model S и Tesla Model X.": "The Tesla Model 3 sedan was introduced on March 31, 2016. The five-seat car was created on a new platform, different from that used in the Tesla Model S and Tesla Model X.",
    "VOYAH FREE — автомобиль, сочетающий в себе высокие технологии и заботу об окружающей среде. По дизайну он напоминает роскошную яхту — чистота линий и минимум элементов. Коэффициент лобового сопротивления 0,28 обеспечивает высокую аэродинамику.": "VOYAH FREE is a car that combines high technology and care for the environment. By design, it resembles a luxury yacht - clean lines and a minimum of elements. A drag coefficient of 0.28 ensures high aerodynamics.",
}

// translateDynamic(); not an optimization

if (document.URL.includes("catalog-en")) {
    console.log(document.URL);
    translateToEN();
}

function translateToEN() {
    translateDynamic();

    // бензинивий / гібрид / електро
    let fuel_des = document.getElementsByClassName('card-fuel');
    for (let i = 0; i < fuel_des.length; i++) {
        fuel_des[i].textContent = (fuel_des[i].textContent in reservedValues ?
            reservedValues[fuel_des[i].textContent] :
            fuel_des[i].textContent);
    }

    // комплектація і колір
    let complectations = document.getElementsByClassName('card-option-text');
    for (let i = 0; i < complectations.length; i++) {
        complectations[i].textContent = (complectations[i].textContent in reservedValues ?
            reservedValues[complectations[i].textContent] :
            complectations[i].textContent);
    }

    // детальніше
    let more = document.getElementsByClassName('btn-text');
    for (let i = 0; i < more.length; i++) {
        more[i].textContent = (more[i].textContent in reservedValues ?
            reservedValues[more[i].textContent] :
            more[i].textContent);
    }

    // let dropdownReservedValues = {
    //     "Отсутствуєт": "Absent",
    //     "Автомат/Ручная": "Automatic/Manual",
    //     "больше": "more than",
    //     "до": "up to",
    // }
    // let dropdownsCheckboxes = document.getElementsByClassName("dropdown-list-text");
    // for (let i = 0; i < dropdownsCheckboxes.length; i++) {
    //     for (const [key, value] of Object.entries(dropdownReservedValues)) {
    //         while (dropdownsCheckboxes[i].innerHTML.includes(key)) {
    //             dropdownsCheckboxes[i].innerHTML = dropdownsCheckboxes[i].innerHTML.replace(key, value);
    //         }
    //     }
    // }

    // let hiddenCards = document.getElementsByClassName("card-hidden");
    // for (let i = 0; i < hiddenCards.length; i++) {
    //     for (const [key, value] of Object.entries(dropdownReservedValues)) {
    //         while (hiddenCards[i].innerHTML.includes(key)) {
    //             hiddenCards[i].innerHTML = hiddenCards[i].innerHTML.replace(key, value);
    //         }
    //     }
    // }


    let descriptionsEN = document.getElementsByClassName("card-main-discription-text-en");
    let descriptionsRU = document.getElementsByClassName("card-discription-text");
    for (let i = 0; i < descriptionsEN.length; i++)
    {
        descriptionsEN[i].style.display = "block";
        descriptionsRU[i].style.display = "none";
    }
    
}

function translateDynamic() {
    let descriptions = document.getElementsByClassName('card-main-discription-text-en');

    for (let i = 0; i < descriptions.length; i++) {
        // .replace(/^\s+|\s+$/g, '').replace(/\s\s+/g, ' ') removes unnecessary spaces
        let text = descriptions[i].textContent.replace(/^\s+|\s+$/g, '').replace(/\s\s+/g, ' '); 

        if (text in catalogValues) {   
            descriptions[i].textContent = catalogValues[text];
            continue;
        }
        
        const xhr = new XMLHttpRequest();
        xhr.open("POST", "http://localhost:5000/translate", true);
        xhr.setRequestHeader("Content-Type", "application/json");

        xhr.onload = function () {
            if (xhr.status === 200) {

                const response = JSON.parse(xhr.responseText);
                descriptions[i].textContent = response.translatedText;
                
                if (descriptions[i].textContent.includes('. .')) {
                    descriptions[i].textContent = descriptions[i].textContent.replace('. .', '.');
                }
            } else {
                // error
            }
            
        };

        const requestBody = JSON.stringify({
            q: text,
            source: "ru",
            target: "en",
            format: "text",
            //api_key: "", // Specify your API key here
        });

        xhr.send(requestBody);
    }
}